repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
        files: ^((custom_components|tests)/.+)?[^/]+\.(py|pyi)$