#!/usr/bin/env python3
"""Read upstream versions and summarize the non-blocking backend canary.

No installation, host access, repository mutation, or issue writes occur here.
The workflow owns candidate installation and optional scheduled issue reporting.
"""

from __future__ import annotations

import argparse
import collections
import importlib.metadata
import json
import os
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

from packaging.requirements import Requirement
from packaging.version import InvalidVersion, Version

PYPI_URL = "https://pypi.org/pypi/pymammotion/json"
UPSTREAM_RELEASE_URL = (
    "https://api.github.com/repos/mikey0000/Mammotion-HA/releases/latest"
)
PIN_TEST = (
    "tests_ha.test_pymammotion_pin::test_installed_pymammotion_is_the_pinned_version"
)


def fetch_json(url: str) -> dict[str, Any]:
    """Read only fixed public endpoints, with bounded time and response size."""
    headers = {
        "User-Agent": "Chorty-Mammotion-backend-canary",
        "Accept": "application/json",
    }
    token = os.environ.get("GITHUB_TOKEN")
    if url.startswith("https://api.github.com/") and token:
        headers["Authorization"] = f"Bearer {token}"
    request = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(request, timeout=30) as response:
        data = response.read(16_000_001)
    if len(data) > 16_000_000:
        raise ValueError("Upstream metadata response exceeds 16 MB")
    result = json.loads(data)
    if not isinstance(result, dict):
        raise TypeError("Expected a JSON object")
    return result


def latest_stable(metadata: dict[str, Any]) -> str:
    """Select a released, non-yanked stable version; never a preview or empty release."""
    candidates = []
    for value, files in metadata["releases"].items():
        try:
            version = Version(value)
        except InvalidVersion:
            continue
        if version.is_prerelease or version.is_devrelease:
            continue
        if files and any(not entry.get("yanked", False) for entry in files):
            candidates.append(version)
    if not candidates:
        raise ValueError("PyPI has no non-yanked stable pymammotion release")
    return str(max(candidates))


def backend_pin(manifest: dict[str, Any]) -> str:
    """Extract exactly one pinned backend distribution from an integration manifest."""
    requirements = [Requirement(value) for value in manifest["requirements"]]
    backends = [value for value in requirements if value.name.lower() == "pymammotion"]
    if len(backends) != 1:
        raise ValueError("Manifest must contain exactly one pymammotion requirement")
    requirement = backends[0]
    if requirement.url:
        match = re.search(
            r"/pymammotion-([^-/?#]+)-py3-none-any\.whl$", requirement.url
        )
        if match:
            return str(Version(match[1]))
    pins = list(requirement.specifier)
    if len(pins) == 1 and pins[0].operator == "==" and "*" not in pins[0].version:
        return str(Version(pins[0].version))
    raise ValueError(
        "pymammotion requirement must be an exact version or versioned wheel"
    )


def snapshot(root: Path) -> dict[str, Any]:
    """Capture our shipped pin, its upstream base, PyPI latest, and upstream HA's pin."""
    shipped_manifest = json.loads(
        (root / "custom_components/mammotion/manifest.json").read_text()
    )
    shipped = backend_pin(shipped_manifest)
    latest = latest_stable(fetch_json(PYPI_URL))
    release = fetch_json(UPSTREAM_RELEASE_URL)
    tag = release["tag_name"]
    if not isinstance(tag, str) or not re.fullmatch(r"[A-Za-z0-9._-]+", tag):
        raise ValueError("Unexpected upstream release tag")
    manifest_url = f"https://raw.githubusercontent.com/mikey0000/Mammotion-HA/{tag}/custom_components/mammotion/manifest.json"
    upstream_pin = backend_pin(fetch_json(manifest_url))
    base = Version(shipped).base_version
    return {
        "shipping_version": shipped,
        "fork_base_version": base,
        "latest_upstream_version": latest,
        "upstream_ha_release": tag,
        "upstream_ha_backend_version": upstream_pin,
        "drift": base != latest or base != upstream_pin,
        "sources": {
            "pypi": PYPI_URL,
            "upstream_release": release["html_url"],
            "upstream_manifest": manifest_url,
        },
    }


def suite_summary(path: Path) -> dict[str, Any]:
    """Keep every failure visible, separating only the intentional installed-pin mismatch."""
    if not path.exists():
        return {
            "available": False,
            "reason": "No JUnit XML: inspect installation/collection logs",
        }
    # JUnit is generated by this job's own pytest invocation, not downloaded.
    root = ET.parse(path).getroot()  # noqa: S314
    suites = [root] if root.tag == "testsuite" else list(root.iter("testsuite"))
    failures = []
    for case in root.iter("testcase"):
        failure = case.find("failure")
        if failure is not None:
            name = f"{case.get('classname')}::{case.get('name')}"
            failures.append({"test": name, "message": failure.get("message", "")})
    counts = {
        key: sum(int(suite.get(key, "0")) for suite in suites)
        for key in ("tests", "failures", "errors", "skipped")
    }
    pin = [failure for failure in failures if failure["test"] == PIN_TEST]
    compatibility = [failure for failure in failures if failure["test"] != PIN_TEST]
    groups = collections.Counter(
        failure["test"].split("::")[0] for failure in compatibility
    )
    return {
        "available": True,
        **counts,
        "passed": counts["tests"]
        - counts["failures"]
        - counts["errors"]
        - counts["skipped"],
        "expected_pin_failures": pin,
        "compatibility_failures": compatibility,
        "failure_groups": dict(sorted(groups.items())),
    }


def render_summary(metadata: dict[str, Any], results: dict[str, Any]) -> str:
    """Explain the canary result without presenting it as hardware qualification."""
    lines = [
        "## Upstream backend canary (non-blocking)",
        "",
        f"Shipping: `{metadata['shipping_version']}`; fork base: `{metadata['fork_base_version']}`.",
        f"PyPI stable candidate: `{metadata['latest_upstream_version']}`.",
        f"Upstream HA `{metadata['upstream_ha_release']}` pins `{metadata['upstream_ha_backend_version']}`.",
        "",
    ]
    installed = results.get("installed_pymammotion")
    if installed:
        lines.extend([f"Backend actually tested: `{installed}`.", ""])
        if installed != metadata["latest_upstream_version"]:
            lines.extend(
                [
                    "**Candidate installation mismatch: these results do not test the resolved upstream candidate.**",
                    "",
                ]
            )
    if results["available"]:
        lines.extend(
            [
                f"Tests: **{results['passed']} passed, {results['failures']} failed, {results['errors']} errors, {results['skipped']} skipped**.",
                f"Expected installed-pin mismatches: **{len(results['expected_pin_failures'])}** (retained in the raw suite).",
                f"Compatibility failures: **{len(results['compatibility_failures'])}**.",
                "",
                "| Test module | Compatibility failures |",
                "| --- | ---: |",
            ]
        )
        lines.extend(
            f"| `{module}` | {count} |"
            for module, count in results["failure_groups"].items()
        )
    else:
        lines.append(results["reason"])
    lines.extend(
        [
            "",
            "Inspect the artifact for dependency checks, package versions, logs, and individual failures.",
            "Fixture-driven passes do not establish native position-stream support or BLE cleanup behavior.",
            "This job changes no shipping pin and never authorizes a deployment or real motion.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    """Capture a read-only version snapshot or summarize local JUnit output."""
    parser = argparse.ArgumentParser(description=__doc__)
    subcommands = parser.add_subparsers(dest="command", required=True)
    capture = subcommands.add_parser("snapshot")
    capture.add_argument("--root", type=Path, default=Path("."))
    capture.add_argument("--output", type=Path, required=True)
    report = subcommands.add_parser("summary")
    report.add_argument("--snapshot", type=Path, required=True)
    report.add_argument("--junit", type=Path, required=True)
    report.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    if args.command == "snapshot":
        result = snapshot(args.root)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps(result, indent=2) + "\n")
        with open(os.environ.get("GITHUB_OUTPUT", os.devnull), "a") as output:
            output.write(f"candidate={result['latest_upstream_version']}\n")
            output.write(f"drift={str(result['drift']).lower()}\n")
        print(json.dumps(result, indent=2))
    else:
        metadata = json.loads(args.snapshot.read_text())
        result = suite_summary(args.junit)
        result["installed_pymammotion"] = importlib.metadata.version("pymammotion")
        args.output.write_text(json.dumps(result, indent=2) + "\n")
        text = render_summary(metadata, result)
        with open(os.environ.get("GITHUB_STEP_SUMMARY", os.devnull), "a") as output:
            output.write(text)
        print(text)


if __name__ == "__main__":
    try:
        main()
    except (TypeError, ValueError, KeyError, OSError) as error:
        print(f"Canary metadata/report failed: {error}", file=sys.stderr)
        raise SystemExit(1) from error
