   name: Crowdin Action

   on:
     push:
       branches: [ main, dev ]
     pull_request:
     workflow_dispatch: # This enables manual triggering
       inputs:
         upload_sources:
           description: 'Upload sources to Crowdin'
           required: true
           default: 'true'
         upload_translations:
           description: 'Upload translations to Crowdin'
           required: true
           default: 'true'
         download_translations:
           description: 'Download translations from Crowdin'
           required: true
           default: 'true'

   jobs:
     synchronize-with-crowdin:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout
           uses: actions/checkout@v2

         - name: crowdin action
           uses: crowdin/github-action@v2
           with:
             upload_sources: true
             upload_translations: false
             download_translations: true
             localization_branch_name: l10n_crowdin_translations
             create_pull_request: true
             pull_request_title: 'New Crowdin translations'
             pull_request_body: 'New Crowdin pull request with translations'
             pull_request_labels: 'crowdin, i18n'
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             CROWDIN_MAMMOTION_TOKEN: ${{ secrets.CROWDIN_MAMMOTION_TOKEN }}